### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by PandaUprising** [PandaUprising/SetSpawn#1]
Add a cooldown option for the /spawn command

**Comment by Anipoki** [comment]
How to use cooldown option?

**Comment by PandaUprising** [comment]
> How to use cooldown option?

I am still working out how to add it, should be done soon!

**Comment by PandaUprising** [comment]
> How to use cooldown option?

It is done now if you want to build it of github but I'm not going to fully release it just yet, still got a few more things to add

Edit: If you want the pre-release go to the releases tab, it won't be on spigot.org

**Comment by PandaUprising** [comment]
Done

**Comment by Anipoki** [comment]
Super, but if you can add setting to change time of cooldown it be greate ^_^

**Comment by PandaUprising** [comment]
Is this for the latest release or for the original cooldown option?

**Comment by Anipoki** [comment]
Last release.

**Comment by PandaUprising** [comment]
There should be an option for that, the default is 3 seconds

**Comment by Anipoki** [comment]
I can't find it :-(   Where i must search?

**Comment by PandaUprising** [comment]
Can you send me a screenshot?

**Comment by Anipoki** [comment]
What exactly is this screenshot supposed to be?

**Comment by PandaUprising** [comment]
The config.yml file

**Comment by Anipoki** [comment]
![config](https://github.com/PandaUprising/SetSpawn/assets/111339418/fbd68bab-0dc8-4976-950e-ac0e0d6fd355)
This is my config file in my server.

**Comment by PandaUprising** [comment]
hmm, it seems like the other config like the messages didn't load, are they there or not?

**Comment by Anipoki** [comment]
No, there is only one file in "SetSpawn" directory, "config.yml"

**Comment by PandaUprising** [comment]
Sorry for the late reply, yes there should be only 1 file, but there should be more things in that file. Are the spawn cords the only thing in that file?

**Comment by Anipoki** [comment]
Sorry for the loooong late reply :) Yes. It's only spawn coords in this file. I delete this file and restart server, then set spawn point and my new file is the same like previous.

**Comment by ghost** [comment]
@Anipoki This has been fixeed by the pull request #8. Thanks for letting me know about this!
