### ISSUE TITLE
Feature Request: Improvements / Reworks

### ISSUE THREAD

**Issue by DontBlameMe99** [PandaUprising/SetSpawn#10]
Hello PandaUprising!

I would like to implement some changes to this plugin, but I first want to make sure that you are interested.

Here are the changes I propose:

- Replace all Paragraph-Symbol colors (e.g., §4, etc.) or ChatColor.SOMETHING colors with the new and maintained [MiniMessage from Kyori](https://docs.advntr.dev/minimessage/format.html) (this is built-in, so no extra library is needed).
- Remove all unused items from the config and add other necessary messages.
- Improve the formatting of the teleporting message (make it customizable and not just a number).
- Add consistent line breaks/line formatting (currently, there are some random empty lines in the files that make no sense).

If you would like me to work on this, please let me know!

**Comment by PandaUprising** [comment]
Yes that would be amazing! Thanks so much for your offer. I have been very busy with life recently so have not had time to update the plugin. Your help would be greatly appreciated!
