### ISSUE TITLE
TeleportOnJoin

### ISSUE THREAD

**Issue by Nukecraft5419** [PandaUprising/SetSpawn#6]
Hi could you add that when one enters it teleports him to the spawn

**Comment by PandaUprising** [comment]
Sure! I can work on that, make sure to look out in the next release!

**Comment by Nukecraft5419** [comment]
Thank you very much, as soon as you do the release I'll leave the plugin that I'm using now which is TSetSpawn and I don't trust it so much it only has 2 downloads and it's not who knows that yours is perfect but that's all that's missing

**Comment by PandaUprising** [comment]
Thx for the feedback, will work on this over the coming days, shouldn't take too long to add!

**Comment by PandaUprising** [comment]
> Thx for the feedback, will work on this over the coming days, shouldn't take too long to add!
I'll add it when I release the 1.20.3 version, or earlier, depends how much longer until the 1.20.3 release

**Comment by Nukecraft5419** [comment]
Will the plugin also be compatible for 1.8?

**Comment by PandaUprising** [comment]
It should be, yes

**Comment by Nukecraft5419** [comment]
perfect thank you very much

**Comment by PandaUprising** [comment]
The code is written, just need to test it and publish it, should be done by the weekend at latest!

**Comment by Nukecraft5419** [comment]
Perfect

**Comment by PandaUprising** [comment]
Might just wait until Minecraft 1.21 comes out, as that doesn't seem too far away, and will give me time to make sure everything works

**Comment by Nukecraft5419** [comment]
I will wait for your updated plugin to come out see when you get it out

**Comment by PandaUprising** [comment]
New update for the plugin should drop later today or early tomorrow
