### ISSUE TITLE
How do I allow people to tp back to spawn even if they arent a server operator?

### ISSUE THREAD

**Issue by Clyde6790pGIT** [PandaUprising/SetSpawn#9]
I've noticed my friends complaining about it not allowing them and I cant figure out how to allow normal people to use this command

**Comment by PandaUprising** [comment]
Make sure the player has the permission
setspawn.spawn

**Comment by Clyde6790pGIT** [comment]
Hi, the command you provided just sends me to the spawn and trying it on a deopped account says "You do not have permission" or something within the lines of that.

**Comment by PandaUprising** [comment]
Does the deopped account have the permission setspawn.spawn?

**Comment by Clyde6790pGIT** [comment]
Hi, how do you check if they have permission? and how do you give permission to them?

**Comment by PandaUprising** [comment]
I recommend a plugin called Luck perms, it is super useful when handling permissions and real easy to use.
https://www.spigotmc.org/resources/luckperms.28140/

**Comment by Clyde6790pGIT** [comment]
Hi, the issue has been solved thanks to the plugin you provided.
